### ISSUE TITLE
Race condition, tmp siva files deleted too soon

### ISSUE THREAD

**Issue by erizocosmico** [src-d/spark-api#44]
Executing the python tests I noticed randomly they fail because the tmp siva files cannot be found so this looks like a race condition somewhere (could very well be a Py4J/pyspark thing, so if you think this is not related to our code I can investigate further to see what's going on the py side)

Stacktrace of the crash:

```
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/29/temp_shuffle_2fe14279-9444-431b-9392-4bf715b284d9
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/29/temp_shuffle_2fe14279-9444-431b-9392-4bf715b284d9 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/29/temp_shuffle_2fe14279-9444-431b-9392-4bf715b284d9
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/28/temp_shuffle_649e8ea0-e7ff-4e72-b5d5-f2eec176dd46
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/28/temp_shuffle_649e8ea0-e7ff-4e72-b5d5-f2eec176dd46 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/28/temp_shuffle_649e8ea0-e7ff-4e72-b5d5-f2eec176dd46
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/3e/temp_shuffle_247a46ff-753f-4a69-8c6b-fed143266a01
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/3e/temp_shuffle_247a46ff-753f-4a69-8c6b-fed143266a01 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/3e/temp_shuffle_247a46ff-753f-4a69-8c6b-fed143266a01
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/02/temp_shuffle_15d14d72-f4f0-44e4-8c32-4998fa803dff
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/02/temp_shuffle_15d14d72-f4f0-44e4-8c32-4998fa803dff (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/02/temp_shuffle_15d14d72-f4f0-44e4-8c32-4998fa803dff
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/38/temp_shuffle_dd1b5a5a-7226-4578-aaa9-1086dd67594e
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/38/temp_shuffle_dd1b5a5a-7226-4578-aaa9-1086dd67594e (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/38/temp_shuffle_dd1b5a5a-7226-4578-aaa9-1086dd67594e
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/3d/temp_shuffle_ef432a77-5e65-4f6d-96ed-b5b5965e58f8
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/3d/temp_shuffle_ef432a77-5e65-4f6d-96ed-b5b5965e58f8 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/3d/temp_shuffle_ef432a77-5e65-4f6d-96ed-b5b5965e58f8
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/29/temp_shuffle_69c5fa7d-a6f6-4d9d-a943-9816db1d5518
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/29/temp_shuffle_69c5fa7d-a6f6-4d9d-a943-9816db1d5518 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/29/temp_shuffle_69c5fa7d-a6f6-4d9d-a943-9816db1d5518
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/20/temp_shuffle_692f2eae-7e3b-43e5-9e7e-1fc7310787fb
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/20/temp_shuffle_692f2eae-7e3b-43e5-9e7e-1fc7310787fb (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/20/temp_shuffle_692f2eae-7e3b-43e5-9e7e-1fc7310787fb
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/33/temp_shuffle_7e094f01-8975-4983-a60c-2c6b13fa28dc
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/33/temp_shuffle_7e094f01-8975-4983-a60c-2c6b13fa28dc (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/33/temp_shuffle_7e094f01-8975-4983-a60c-2c6b13fa28dc
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/11/temp_shuffle_99570036-ad3f-40c1-8971-f8aa09263446
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/11/temp_shuffle_99570036-ad3f-40c1-8971-f8aa09263446 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/11/temp_shuffle_99570036-ad3f-40c1-8971-f8aa09263446
17/09/19 15:24:30 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/24/temp_shuffle_28e739f9-a3d0-462d-b71f-4196351aefef
java.io.FileNotFoundException: /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/24/temp_shuffle_28e739f9-a3d0-462d-b71f-4196351aefef (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.apache.spark.storage.DiskBlockObjectWriter$$anonfun$revertPartialWritesAndClose$2.apply$mcV$sp(DiskBlockObjectWriter.scala:215)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1346)
	at org.apache.spark.storage.DiskBlockObjectWriter.revertPartialWritesAndClose(DiskBlockObjectWriter.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.stop(BypassMergeSortShuffleWriter.java:237)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:102)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17/09/19 15:24:30 ERROR BypassMergeSortShuffleWriter: Error while deleting file /tmp/blockmgr-86a0b5f1-6b06-4e0f-8cb3-a7994b0c6f2e/24/temp_shuffle_28e739f9-a3d0-462d-b71f-4196351aefef
```

**Comment by erizocosmico** [comment]
This seems to have disappeared for me after latest rebases, but who knows, maybe it's still there lurking in the shadows, so I'd keep it open anyway until we further investigate this issue.

**Comment by erizocosmico** [comment]
I've been trying to reproduce this error again with the current state of master but could not. Closing this, since it appears to have disappeared.
